import type { Config } from "tailwindcss";

export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#EFECE2",
        "surface": "#F8F6F0",
        "primary": "#3B4D2B",
        "on-primary-fixed": "#1F2916",
        "surface-variant": "#E4DFD2",
        "on-secondary-fixed": "#1F2916",
        "on-primary": "#F8F6F0",
        "surface-bright": "#FAF8F3",
        "surface-dim": "#DDD8C7",
        "secondary-fixed-dim": "#A7B893",
        "outline": "#868F7D",
        "on-surface-variant": "#4A5243",
        "tertiary-fixed": "#E1E8D5",
        "secondary-container": "#4F6438",
        "on-tertiary": "#FFFFFF",
        "secondary-fixed": "#E1E8D5",
        "on-tertiary-fixed-variant": "#374825",
        "primary-fixed-dim": "#A7B893",
        "on-error": "#FFFFFF",
        "on-error-container": "#410002",
        "inverse-surface": "#1F2916",
        "surface-container-high": "#E6E2D4",
        "secondary": "#4F6438",
        "outline-variant": "#C7C0B0",
        "inverse-primary": "#A7B893",
        "surface-container-low": "#F5F3EC",
        "on-secondary": "#FFFFFF",
        "on-primary-container": "#F8F6F0",
        "inverse-on-surface": "#F8F6F0",
        "on-surface": "#1E231A",
        "error": "#BA1A1A",
        "background": "#F8F6F0",
        "on-tertiary-container": "#1F2916",
        "on-secondary-fixed-variant": "#3B4D2B",
        "surface-tint": "#3B4D2B",
        "primary-fixed": "#E1E8D5",
        "primary-container": "#1F2916",
        "on-background": "#1E231A",
        "on-secondary-container": "#F8F6F0",
        "error-container": "#FFDAD6",
        "tertiary-container": "#E1E8D5",
        "surface-container-highest": "#DDD8C7",
        "on-tertiary-fixed": "#1F2916",
        "tertiary-fixed-dim": "#A7B893",
        "surface-container-lowest": "#FFFFFF",
        "tertiary": "#627050",
        "on-primary-fixed-variant": "#3B4D2B"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
} satisfies Config;
